name = "Trusty"
uuid = "8d423e50-a21a-41c9-877a-e99e491e0514"
authors = ["Andrew Solanto <atsolanto@gmail.com>"]
version = "0.1.0"

[deps]
AngleBetweenVectors = "ec570357-d46e-52ed-9726-18773498274d"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AngleBetweenVectors = "0.3.0"
Graphs = "1.6.0"
InvertedIndices = "1.1.0"
MetaGraphs = "0.7.1"
PaddedViews = "0.5.11"
Plots = "1.27.6"
Rotations = "1.3.0"
Unitful = "1.11.0"
julia = "1.7"
